server.port: 8765

spring:
  application.name: gateway-server
  security.oauth2.resourceserver.jwt.issuer-uri: http://auth-server:9000
  cloud:
    gateway:
      discovery.locator.enabled: true
#      routes:
#        - id: ProductsService
#          uri: "lb://products-service/"
#          predicates:
#            - Path=/products/**
#          filters:
#            - AddRequestHeader=added-request-header, added-request-header-value
#            - AddResponseHeader=added-response-header, added-response-header-value
#        - id: OrdersService
#          uri: "lb://orders-service/"
#          predicates:
#            - Path=/orders/**


eureka.client:
  service-url.default-zone: http://localhost:8761/eureka
  health-check.enabled: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

