version: '3.8'
services:
  config-server:
    image: ricardoahumada/config-server:0.0.1-SNAPSHOT
    build: config-server/
    environment:
      - eureka.client.service-url.defaultZone=http://naming-server:8761/eureka    
    ports:
      - 8888:8888
    networks:
      - spring-cloud-network
  naming-server:
    image: ricardoahumada/naming-server:0.0.1-SNAPSHOT
    build: naming-server/
    depends_on:
      - config-server
    environment:
      - spring.config.import=optional:configserver:http://config-server:8888  
    ports:
      - 8761:8761
    networks:
      - spring-cloud-network
  gateway-server:
    image: ricardoahumada/gateway-server:0.0.1-SNAPSHOT
    build: gateway-server/
    depends_on:
      - naming-server
    environment:
      - eureka.client.service-url.defaultZone=http://naming-server:8761/eureka   
    ports:
      - 8765:8765
    networks:
      - spring-cloud-network
  products-service:
    build: products-service/
    image: ricardoahumada/products-service:0.0.1-SNAPSHOT
    depends_on:
      - naming-server
    environment:
      - eureka.client.service-url.defaultZone=http://naming-server:8761/eureka   
    ports:
      - "9090-9099:9090"
    scale: 1
    networks:
      - spring-cloud-network    
  orders-service:
    image: ricardoahumada/orders-service:0.0.1-SNAPSHOT
    build: orders-service/
    depends_on:
      - naming-server
      - products-service
      - config-server
    environment:
      - eureka.client.service-url.defaultZone=http://naming-server:8761/eureka   
      - spring.config.import=optional:configserver:http://config-server:8888   
    ports:
      - 9100:9100
    networks:
      - spring-cloud-network

networks:
    spring-cloud-network:
        driver: bridge      