spring.application.name: config-server
server.port: 8888

#Git repo location
spring.cloud.config.server.git:
  uri: "https://github.com/ricardoahumada/spring-cloud-config-repo"
  default-label: master

eureka.client.service-url.default-zone: http://naming-server:8761/eureka
