spring.application.name: naming-server
server.port: 8761

cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      enabled: true

spring.config:
  config: false
  import: "optional:configserver:http://localhost:8888" # config server

eureka.client.register-with-eureka: false
eureka.client.fetch-registry: false

