spring:
  application.name: ProductsService
  profiles.active: dev
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

spring.mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER
app.jwt.secret: SECRET-KEY-VALUE
---
spring:
  sql.init.mode: always
  profiles: dev
  application:
    name: ProductsService
  datasource:
    url: "jdbc:h2:mem:productsdb"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2-ui

server:
  port: 9090

#debug: true
logging:
  path: /var/tmp/
  file: /var/tmp/mylog.log
  level:
    root: INFO


---
spring:
  profiles: prod
  application:
    name: ProductsService
server:
  port: 8443
  ssl:
    key-store: keystore.p12
    key-store-password: pa55wrd
    keyStoreType: PKCS12
    keyAlias: tomcat
security.require-ssl: true

