server.port: 8765

spring:
  application.name: gateway-server
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: ProductsService
          uri: "lb://products-service/"
          predicates:
            - Path=/products/**
        - id: OrdersService
          uri: "lb://orders-service/"
          predicates:
            - Path=/orders/**        

eureka.client:  
  service-url.default-zone: http://naming-server:8761/eureka
  health-check.enabled: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway